### PR TITLE
ffmpeginterface: Fix subtitles under windows

### PR DESCRIPTION
**Pull request by patrickelectric**
There is a problem related to relative and global paths with
subtitles in ffmpeg.
For more information, check: https://trac.ffmpeg.org/ticket/3334

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
Ping @jcabrerav

**Comment by lfdominguez** [comment]
Your commits must be signed to allow merge

**Comment by patrickelectric** [comment]
@lfdominguez But they are, no ?

**Comment by patrickelectric** [comment]
@lfdominguez ping

**Comment by patrickelectric** [comment]
ping @lfdominguez

**Comment by lfdominguez** [comment]
> @lfdominguez But they are, no ?

image

**Comment by patrickelectric** [comment]
Oh, is the gpg signature and not normal signatures, thanks !

**Pull request merged**
